site_name: Biomedical Research Hub Documentation
site_url: https://brh.data-commons.org/
repo_url: https://github.com/uc-cdis/BRH-documentation
nav:
  - Return to BRH Platform: https://brh.data-commons.org/
  - Home: 01-home.md
  - How to Get Started:
    - Quickstart - BRH Overview: 04-BRH_overview.md
    - Workspace Page (Registration): 05-workspace_registration.md
    - Login Page: 06-loginoverview.md
    - Check Study Access and Authorize Resources: 07-how_to_check_request_access.md
    - Discovery Page: 08-discovery_page.md
    - Profile Page: 10-profile_page.md
  - Workspace User Guide:
    - Getting Started in Workspace : 09-workspace_page.md
    - Workspace Accounts - Trial and Persistent Pay Models (STRIDES, Direct Pay): 13-workspace_accounts.md
    - Launch a Workspace with a Persistent Pay Model: 14-lauch_with_persistent_paymodel.md
    - Monitor Compute Usage in Persistent Pay Models: 15-monitor_compute_usage.md
    - If Compute Usage Exceeds Funding: 16-usage_exceeds_funding.md
    - Downloading Data Files: 11-downloading_data_files.md
    - Workspace FAQ: 17-workspace_faq.md
  - FAIR Data: 02-types_of_shared_data.md
  - Data Management and Repositories: 03-data_and_repos.md
  - Contact: 12-contact.md
  - '':
    - Nextflow - Getting Started: nextflow-getting-started.md
    - Nextflow - Tutorial Workflows: nextflow-tutorial workflows.md
    - Nextflow - Create Dockerfile: nextflow-create-docker.md
    - Nextflow - Request Credentials: nextflow-request-creds.md
    - Nextflow - Upload Dockerfile: nextflow-upload-docker.md

theme:
  favicon: img/favicon.ico
  logo: img/brh-logo.png
  name: material

  palette:

   # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: brh_platform
      toggle:
        icon: material/eye
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: brh_platform_dark
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tracking
extra_css:
  - stylesheets/extra.css
use_directory_urls: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: True
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - search
  - mkdocs-video:
      is_video: True
