site_name: BRH Markdown Test - QA v0.0
site_url: https://qa-brh.planx-pla.net
repo_url:
nav:
  - Home: home.md
  - Return to BRH Platform: https://brh.data-commons.org/
  - Types of Shared Data: types_of_shared_data.md
  - Data Management and Repositories: data_and_repos.md
  - How to Get Started:
    - BRH Overview: BRH_overview.md
    - Workspace Registration: workspace_registration.md
    - Login Page: loginoverview.md
    - How to Check Request Access: how_to_check_request_access.md
    - Discovery Page: discovery_page.md
    - Workspaces Page: workspace_page.md
    - Profile Page: profile_page.md
  - Downloading Data Files: downloading_data_files.md
  - Contact: contact.md

theme:
  favicon: img/favicon.ico
  logo: img/brh-logo.png
  name: material

  palette:

   # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: brh_platform
      toggle:
        icon: material/eye
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: brh_platform_dark
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tracking
extra_css:
  - stylesheets/extra.css
use_directory_urls: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: True
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - search
  - mkdocs-video:
      is_video: True

